server:
  port: 8080
  tomcat:
    threads:
      max: 5
    mbeanregistry:
      enabled: true
    remoteip:
      protocol-header: x-forwarded-proto
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/html,text/xml
    min-response-size: 1KB
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
  shutdown: graceful
spring:
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  mvc:
    servlet:
      path: /
      load-on-startup: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
logging:
  level:
    root: info