server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/html,text/xml
    min-response-size: 1KB
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  resources:
    cache:
      period: 1h
    chain:
      cache: true
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
logging:
  level:
    root: info